config/routes.rb
Rails.application.routes.draw do
  resources :weins
  root 'weins#index'
  resources :searches

end

app/models/wein.rb
class Wein < ActiveRecord::Base

  #  def self.search(search)
 #       if search
   #         where(["name LIKE ?","%#{params[:search]}%"]).order("price ASC")
  #      else all
 #       end
 #   end
 
# self.default_scope order('price') 




belongs_to :shop
end

app/controllers/weins_controller.rb
class WeinsController < ApplicationController
  before_action :set_wein, only: [:show, :edit, :update, :destroy]
  # GET /weins
  # GET /weins.json
  def index
   # @weins = Wein.all.page(params[:page]).per(42)
   @weins = Wein.where(["name LIKE ?","%#{params[:search]}%"]).page(params[:page]).per(42)
     #@weins = Wein.all.order('price')
     #@weins  = Wein.all.order(:price)
     # @weins = Wein.where(["name LIKE ?","%#{params[:search]}%"]).order(price: :asc)
     #@weins = @weins.sort { |a, b| a.price <=> b.price }
    #@prices = @weins.pluck(:price).map { |p| sprintf("€%2.2f", p) }
     
   #  .order(price: :asc)
#@prices = @products.pluck(:price).map { |p| sprintf("€%2.2f", p) }
  end

  # GET /weins/1
  # GET /weins/1.json
  def show
  end

  # GET /weins/new
  def new
    @wein = Wein.new
  end

  # GET /weins/1/edit
  def edit
  end

  # POST /weins
  # POST /weins.json
  def create
    @wein = Wein.new(wein_params)

    respond_to do |format|
      if @wein.save
        format.html { redirect_to @wein, notice: 'Wein was successfully created.' }
        format.json { render :show, status: :created, location: @wein }
      else
        format.html { render :new }
        format.json { render json: @wein.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weins/1
  # PATCH/PUT /weins/1.json
  def update
    respond_to do |format|
      if @wein.update(wein_params)
        format.html { redirect_to @wein, notice: 'Wein was successfully updated.' }
        format.json { render :show, status: :ok, location: @wein }
      else
        format.html { render :edit }
        format.json { render json: @wein.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weins/1
  # DELETE /weins/1.json
  def destroy
    @wein.destroy
    respond_to do |format|
      format.html { redirect_to weins_url, notice: 'Wein was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wein
      @wein = Wein.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wein_params
      params.require(:wein).permit(:name, :image_url, :price, :vintage)
    end
end

app/helpers/weins_helper.rb
module WeinsHelper
end

app/views/weins/_form.html.erb
<%= form_for(@wein) do |f| %>
  <% if @wein.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wein.errors.count, "error") %> prohibited this wein from being saved:</h2>

      <ul>
      <% @wein.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :vintage %><br>
    <%= f.text_field :vintage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weins/edit.html.erb
<h1>Editing Wein</h1>

<%= render 'form' %>

<%= link_to 'Show', @wein %> |
<%= link_to 'Back', weins_path %>

app/views/weins/home.html.erb
<body>
<div class="jumbotron">
<div class="container">
    
    <div class="search">
    <h3>Weine. Günstiger.</h3>

  <%= form_tag weins_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search],  class:"form-control", placeholder: "Suchen" %>
  <%= submit_tag "Suchen", class: "jhp" %>
  <% end %>
  </div>
  <%= link_to "Advanced Search", new_search_path %></div>
</div>
</body>

app/views/weins/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="description" content="Tease and Denial Videos only - The largest collection of Tease and Denial Videos, Ckips and Short Movies on the Web.">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78539272-1', 'auto');
  ga('send', 'pageview');

</script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/shop-homepage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
    <!-- Navigation -->
    <!--<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
    <!--    <div class="container">-->
            <!-- Brand and toggle get grouped for better mobile display -->
    <!--        <div class="navbar-header">-->
    <!--            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">-->
    <!--                <span class="sr-only">Toggle navigation</span>-->
    <!--                <span class="icon-bar"></span>-->
    <!--                <span class="icon-bar"></span>-->
    <!--                <span class="icon-bar"></span>-->
    <!--            </button>-->
    <!--            <a class="navbar-brand" href="#">Start Bootstrap</a>-->
    <!--        </div>-->
            <!-- Collect the nav links, forms, and other content for toggling -->
    <!--        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
    <!--            <ul class="nav navbar-nav">-->
    <!--                <li>-->
    <!--                    <a href="#">About</a>-->
    <!--                </li>-->
    <!--                <li>-->
    <!--                    <a href="#">Services</a>-->
    <!--                </li>-->
    <!--                <li>-->
    <!--                    <a href="#">Contact</a>-->
    <!--                </li>-->
    <!--            </ul>-->
    <!--        </div>-->
            <!-- /.navbar-collapse -->
    <!--    </div>-->
        <!-- /.container -->
    <!--</nav>-->

    <!-- Page Content -->
    
<body>
    <div class="container">

        <div class="row">

            <!--<div class="col-md-3">-->
            <!--    <p class="lead">Shop Name</p>-->
            <!--    <div class="list-group">-->
            <!--        <a href="#" class="list-group-item">Category 1</a>-->
            <!--        <a href="#" class="list-group-item">Category 2</a>-->
            <!--        <a href="#" class="list-group-item">Category 3</a>-->
            <!--    </div>-->
            <!--</div>-->

            <div class="col-md-12">

               
                  <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                <div><%= paginate @weins ,:window => 2 %></div>
                </ul>
            </div>
        </div>
        
                     <% @weins.each do |products| %>
                      <a href=<%= products.source_link %>>
                          <%end%>

             <% @weins.each_slice(4) do |products| %>
                <div class="row">
                      <% products.each do |product| %>
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        <a href=<%= product.source_link %> title="<%= product.name %>">
                        <div class="thumbnail">
                            <%= image_tag(product.image_url, class: 'list_image', size: '260x260', alt: product.name) %>
                            <div class="caption">
                             <!--<h4 class="pull-right">$24.99</h4>-->
                                <p> <%= product.name %>
                                <p>
                                </a>
                                <div class="time"><p><%= product.prod_title %></p></div>
                                
                                
                            </div>
                       
                        </div>
                    </div>
                <%end%>
                  </div>
                    <%end%>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <p>TeaseandDenials.com has a zero-tolerance policy against illegal pornography. All models on this website are 18 years or older. 

Disclaimer: TeaseandDenials.com is a search engine for adult related videos, it only searches for movies found on porn tube sites. 
All the content is added by our crawlers, thumbnails are only linked to the corresponding tube site. The indexing process is completely automated. 

We do not own, produce, host or upload any videos displayed on this website, we only link to them. So if you find any content which should be removed, please contact the corresponding tube site. 
Parents protect your children from adult content with these services: Cyber Patrol, Net Nanny, Cyber Sitter.

Copyright © 2016 TeaseandDenials.com - The Porn Tube Search. All rights reserved.</p>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    
     <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                <div><%= paginate @weins %></div>
                </ul>
            </div>
        </div>
</body>


</html>

app/views/weins/index2.html.erb
<div><%= paginate @weins %></div>




<div class="container">
  <h1 align="center">Listing products</h1>

    <% @weins.each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |product| %>
                <div class="col-lg-3">
                  <a href=<%= product.source_link %>>
                  <%= image_tag(product.image_url, class: 'list_image', size: '260x260') %><br/>
                  <%= product.name %> <br/>
                  <!--<%= product.price %> <br/>-->
                  <!--<%= link_to 'Show', product %><br/>-->
                  </a>
                </div>
            <% end %>    
          </div>
          <hr/>
  <% end %>
</div>

<%= link_to "new", new_wein_path %>

app/views/weins/new.html.erb
<h1>New Wein</h1>

<%= render 'form' %>

<%= link_to 'Back', weins_path %>

app/views/weins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wein.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@wein.image_url, :alt => @wein.image_url, :class => "image_show") %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wein.price %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wein.prod_desc %>
</p>

<p>
  <strong>Vintage:</strong>
  <%= @wein.vintage %>
</p>

<%= link_to 'Edit', edit_wein_path(@wein) %> |
<%= link_to 'Back', weins_path %>